pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn -f Sportvereinsverwaltung/pom.xml clean -DskipTest -U package'
            }
        }
        stage('Test'){
            steps {
                sh 'mvn -f Sportvereinsverwaltung/pom.xml test pmd:pmd'
                junit 'target/surefire-reports/*.xml'
                pmd canRunOnFailed: true, pattern: 'target/pmd.xml'

            }
        }
        stage('Deploy') {
            steps {
                sh 'mvn -DskipTest deploy'
            }
        }
    }
}